# Generated by Django 4.2 on 2023-05-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, to='exercises.author'),
        ),
    ]
